### ISSUE TITLE
Running file-saver command removed XLSX node_module and viceversa

### ISSUE THREAD

**Issue by di3nt3d3l3on** [luwojtaszek/ngx-excel-export#11]
Why Angular-CLI don't get along with both node_modules at same time?

![image](https://user-images.githubusercontent.com/14892912/39537236-89ad6abe-4dfe-11e8-9090-cba7910b8b44.png)

**Comment by luwojtaszek** [comment]
The code was updated and FileSaver was removed from example. File should be saved using `XLSX.writeFile` method.
