### ISSUE TITLE
The file is corrupt

### ISSUE THREAD

**Issue by ivanlopezmolina** [luwojtaszek/ngx-excel-export#3]
I cloned the repository and run it and when trying to open the exported file I get a message saying that the file is corrupt.

**Comment by anhnguyencm** [comment]
i got this issue either , could you show me how to fix it?

**Comment by ivanlopezmolina** [comment]
I haven't fixed it, I think no one is maintaining this repo. :/

**Comment by anhnguyencm** [comment]
god , i used this repo : https://www.npmjs.com/package/json2xlsx-export
and it resolve my issue.

**Comment by itsSandeepNandey** [comment]
I am facing similar issue 'The file is corrupt'

any resolution found yet ?

**Comment by anhnguyencm** [comment]
use this : https://www.npmjs.com/package/json2xlsx-export

**Comment by itsSandeepNandey** [comment]
**Found the solution**  :)

Issue was type attribute for the data I was providing:
 const excelBuffer: any = XLSX.write(workbook, { bookType: 'xlsx', type: '**buffer**' });

I have updated _type:array_  following the below article : 
https://www.npmjs.com/package/xlsx

ex:
 const excelBuffer: any = XLSX.write(workbook, { bookType: 'xlsx', type: '**array**' });

and it started working fine.

Please go through the above article to understand the working of xlsx package.

**Comment by anhnguyencm** [comment]
it's worrking ,! you are great ! ^^

**Comment by adrian5692** [comment]
Same here, I removed file-saver package and used `XLSX.writeFile()` instead of `XLSX.write()`, it downloads the file by itself, no need for other library

**Comment by zaichone** [comment]
@itsSandeepNandey This's work perfectly for me. Thank you.

**Comment by luwojtaszek** [comment]
I updated the code to save the file using XLSX instead of file-saver as suggested above. Tested and it's working fine.
